#!/usr/bin/env bash
#configure domain

info () {
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk \
	-v sub_d="$2" '{print "The subdomain " sub_d " is a " $4 " record and points to " $5}'
}
if [ -z "$2" ]	
then
	for subdomain in www lb-01 web-01 web-02
	do
	info "$1" "$subdomain"
done
else
	info "$1" "$2"
fi
