#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine 
sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo 'Hello World!' > /var/www/html/index.html
