#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine 
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
new="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$new/" /etc/nginx/sites-available/default
sudo service nginx start
