#!/usr/bin/env bash
#configure web-02 to be identical to web-01
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'

#default page
echo 'Hello World!' > /var/www/html/index.html

#redirect page
redir="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$redir/" /etc/nginx/sites-available/default

#error page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
err="error_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$err/" /etc/nginx/sites-enabled/default

#custom header
hostname=$(hostname)
header="server_name _;\n\tadd_header X-Served-By $hostname;"
sed -i "s/server_name _;/$header/" etc/nginx/sites-available/default

sudo service nginx start
