#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

#backend & frontend
beConf="\nbackend web-backend\n\tbalance roundrobin\n\tserver web-01 3.238.171.60 check\n\tserver web-02 3.233.224.138 check"

feConf="\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"

echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
echo $beConf | sudo tee -a /etc/haproxy/haproxy.cfg
echo $feConf | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
