#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get -y update
sudo apt-get -y install haproxy

#backend & frontend
beConf="
backend web-backend
	balance roundrobin
	server web-01 3.238.171.60 check
	server web-02 3.233.224.138 check"

feConf="
frontend http
	bind *:80
	mode http
	default_backend web-backend"

echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
echo $beConf | sudo tee -a /etc/haproxy/haproxy.cfg
echo $feConf | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
