#!/usr/bin/env bash
#debug nginx not listening to port 80
sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo sed -i "s/ ipv6only=on//" /etc/nginx/sites-enabled/default
sudo service nginx start
