#!/usr/bin/env bash
#  configures an Ubuntu server with the below requirements:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.
#+ The checker is running on Docker
echo '127.0.0.2	localhost' > new_host
echo '8.8.8.8	facebook.com' >> new_host
sudo cp new_host /etc/hosts
